/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Controller;

/**
 *
 * @author pauls
 */
public class VistaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form VistaUsuario
     */
    private Controller controladora;
    public VistaUsuario(Controller controladora ) {
        initComponents();
        
        this.controladora=controladora;
        setLocationRelativeTo(null);
        // --- ESTILO ESTÁNDAR ---
        this.setSize(900, 600); // 1. Tamaño fijo (Ancho, Alto)
        this.setResizable(false); // 2. Bloquear para que no lo estiren y se deforme
        this.setLocationRelativeTo(null); // 3. Centrar en la pantalla
        this.setTitle("Sistema de Gestión de Prácticas - UPN"); // 4. Título de la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAdministrativo = new javax.swing.JButton();
        btnPracticante = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(153, 0, 153));

        jPanel1.setBackground(new java.awt.Color(89, 28, 44));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(89, 27, 42));
        jLabel1.setText("SELECCIONE SU PERFIL");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(320, 190, 270, 32);

        btnAdministrativo.setBackground(new java.awt.Color(89, 27, 42));
        btnAdministrativo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdministrativo.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministrativo.setText("ADMINISTRATIVO");
        btnAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrativoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdministrativo);
        btnAdministrativo.setBounds(350, 260, 189, 47);

        btnPracticante.setBackground(new java.awt.Color(89, 27, 42));
        btnPracticante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPracticante.setForeground(new java.awt.Color(255, 255, 255));
        btnPracticante.setText("PRACTICANTE");
        btnPracticante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPracticanteActionPerformed(evt);
            }
        });
        jPanel1.add(btnPracticante);
        btnPracticante.setBounds(350, 340, 193, 45);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/adminisrativo.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(300, 260, 50, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Adobe Express -a file.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 330, 40, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/forma1.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 890, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrativoActionPerformed
        // TODO add your handling code here:
       VistaAdministrativo adm= new VistaAdministrativo(controladora);
       adm.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnAdministrativoActionPerformed

    private void btnPracticanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPracticanteActionPerformed
        // TODO add your handling code here:
        vistaPracticante pract = new vistaPracticante(controladora); 
        pract.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnPracticanteActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrativo;
    private javax.swing.JButton btnPracticante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
