/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Controller;
import javax.swing.JOptionPane;

/**
 *
 * @author pauls
 */
public class VistaAdministrativo extends javax.swing.JFrame {

    /**
     * Creates new form VistaAdministrativo
     */
    private Controller controladora;
    public VistaAdministrativo( Controller controladora) {
        initComponents();
        this.controladora=controladora;
        setLocationRelativeTo(null);
        // --- ESTILO ESTÁNDAR ---
        this.setSize(900, 600); // 1. Tamaño fijo (Ancho, Alto)
        this.setResizable(false); // 2. Bloquear para que no lo estiren y se deforme
        this.setLocationRelativeTo(null); // 3. Centrar en la pantalla
        this.setTitle("Sistema de Gestión de Prácticas - UPN"); // 4. Título de la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtContraseñaAdmin = new javax.swing.JTextPane();
        btnIngresarAdmin = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEmailAdmin = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 350, 150, 25);

        jScrollPane2.setViewportView(txtContraseñaAdmin);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(120, 390, 210, 30);

        btnIngresarAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIngresarAdmin.setText("Ingresar");
        jPanel1.add(btnIngresarAdmin);
        btnIngresarAdmin.setBounds(730, 550, 130, 32);

        btnRegresar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        jPanel1.add(btnRegresar);
        btnRegresar.setBounds(20, 550, 160, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("ingresa tus Datos");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 170, 220, 50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email: ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 260, 100, 25);

        jScrollPane1.setViewportView(txtEmailAdmin);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 300, 200, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Administrativo.1.1.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, -10, 870, 610);

        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 50, 260, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarAdmin;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane txtContraseñaAdmin;
    private javax.swing.JTextPane txtEmailAdmin;
    // End of variables declaration//GEN-END:variables
}
